/**
 * components/editor/message-bubble.tsx
 *
 * Renders a single chat message in the editor's chat panel.
 * User messages are right-aligned with a primary background.
 * AI assistant messages are left-aligned with a card background,
 * rendered as markdown (headings, lists, code blocks, etc.).
 *
 * During streaming, instead of showing raw <file> code blocks,
 * the component shows a GenerationProgress card with:
 * - "Thinking..." spinner before any files are detected
 * - Real-time file list showing which files are being generated
 * - Completion summary when generation finishes
 *
 * Used by: components/editor/chat-panel.tsx
 */

"use client";

import { useMemo, useState } from "react";
import type { ChatMessage, ImageAttachment } from "@/types/chat";
import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Bot, User, Loader2, Wrench, Check, RotateCcw } from "lucide-react";
import { getModelById } from "@/lib/models";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { GenerationProgress } from "./generation-progress";
import {
  Dialog,
  DialogContent,
  DialogTitle,
} from "@/components/ui/dialog";

/**
 * Props for the MessageBubble component.
 *
 * @property message - The chat message to render
 * @property isStreaming - Whether this message is currently being streamed
 */
export interface MessageBubbleProps {
  message: ChatMessage;
  isStreaming?: boolean;
  /** Whether the AI is currently processing this auto-heal request */
  isAutoHealInProgress?: boolean;
}

/**
 * Regex to match <file path="...">content</file> blocks.
 * Used to strip raw file tags from AI messages before display.
 */
const FILE_TAG_REGEX = /<file\s+path="[^"]+">\n?[\s\S]*?\n?<\/file>/g;

/**
 * Regex to match partial/incomplete <file> blocks during streaming.
 * Catches an opening <file> tag without its closing </file>.
 * This prevents half-written code from showing in the chat bubble.
 */
const PARTIAL_FILE_REGEX = /<file\s+path="[^"]+">[\s\S]*$/;

/**
 * Strips <file> XML tags from AI response text for clean chat display.
 * Handles both complete and partial (mid-stream) file blocks.
 *
 * @param content - Raw AI response that may contain <file> tags
 * @param isStreaming - Whether the content is still being streamed
 * @returns Cleaned text with file blocks removed
 */
function stripFileTags(content: string, isStreaming: boolean): string {
  let cleaned = content
    .replace(FILE_TAG_REGEX, "")
    .replace(/\n{3,}/g, "\n\n");

  // Strip partial/incomplete <file> blocks (opening tag without closing tag).
  // Always clean these — old messages saved with fullResponse may have orphans.
  cleaned = cleaned.replace(PARTIAL_FILE_REGEX, "");

  // Strip any leftover closing </file> tags that survived the regex
  cleaned = cleaned.replace(/<\/file>/g, "");

  return cleaned.trim();
}

/**
 * Checks whether the raw content contains any <file> tags.
 * Used to determine if the GenerationProgress card should be shown.
 *
 * @param content - Raw AI response content
 * @returns true if any <file> opening tag is found
 */
function hasFileTags(content: string): boolean {
  return /<file\s+path="/.test(content);
}

/**
 * Formats a model ID string into a human-readable name.
 * Looks up the model in the frontend registry first, then falls
 * back to a simple provider-based name extraction.
 *
 * @param model - The raw model ID string
 * @returns A cleaned-up display name (e.g., "Claude Sonnet 4.5")
 */
function formatModelName(model: string): string {
  // Try the registry first — gives the best display name
  const modelInfo = getModelById(model);
  if (modelInfo) return modelInfo.name;

  // Fallback for old/unknown model IDs
  if (model.includes("claude")) return "Claude";
  if (model.includes("gpt")) return "GPT-4o";
  if (model.includes("gemini")) return "Gemini";
  if (model.includes("deepseek")) return "DeepSeek";
  return model;
}

/**
 * Auto-heal message prefix used to detect auto-heal user messages.
 * These messages are generated by the auto-heal system, not typed by the user.
 */
const AUTO_HEAL_PREFIX = "The app has a build/runtime error";

/**
 * Extracts the attempt number from an auto-heal message.
 * Parses "(attempt X/3)" from the message content.
 *
 * @param content - The message content
 * @returns The attempt number, or 1 as fallback
 */
function extractAttemptNumber(content: string): number {
  const match = content.match(/\(attempt (\d+)\/\d+\)/);
  return match ? parseInt(match[1], 10) : 1;
}

/**
 * Formats an ISO timestamp into a human-readable time string.
 *
 * @param timestamp - ISO 8601 timestamp
 * @returns Formatted time string (e.g., "2:30 PM")
 */
function formatTime(timestamp: string): string {
  return new Date(timestamp).toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  });
}

/**
 * MessageBubble renders a single chat message.
 * User messages appear on the right side in the primary color.
 * AI messages appear on the left side in a card-like container
 * with markdown rendering, generation progress, and optional
 * streaming cursor.
 *
 * @param message - The ChatMessage object to display
 * @param isStreaming - Shows progress indicators if true
 */
export function MessageBubble({ message, isStreaming, isAutoHealInProgress }: MessageBubbleProps) {
  /** Tracks which image is open in the lightbox (null = closed) */
  const [selectedImage, setSelectedImage] = useState<ImageAttachment | null>(null);

  const isUser = message.role === "user";

  /**
   * Clean the AI content for display:
   * - Remove complete <file>...</file> blocks
   * - During streaming, also remove partial/incomplete blocks
   */
  const displayContent = useMemo(() => {
    if (isUser) return message.content;
    return stripFileTags(message.content, !!isStreaming);
  }, [message.content, isUser, isStreaming]);

  /** Whether the AI response contains file blocks (streaming) or persisted changed files (refresh) */
  const showProgress =
    !isUser &&
    (hasFileTags(message.content) ||
      (message.changedFiles && message.changedFiles.length > 0));

  /** Whether the AI is still thinking (streaming but no content yet) */
  const isThinking = isStreaming && !isUser && message.content.length === 0;

  /** Whether this is an auto-heal message generated by the error listener */
  const isAutoHeal =
    isUser && message.content.startsWith(AUTO_HEAL_PREFIX);

  // Render auto-heal messages as system-style cards instead of user bubbles
  if (isAutoHeal) {
    const attempt = extractAttemptNumber(message.content);
    const healDone = !isAutoHealInProgress;

    return (
      <div className="group flex gap-3 animate-fade-in">
        {/* Wrench / Check icon */}
        <div className={cn(
          "flex size-7 shrink-0 items-center justify-center rounded-lg border",
          healDone
            ? "border-green-500/30 bg-green-500/10"
            : "border-amber-500/30 bg-amber-500/10"
        )}>
          {healDone
            ? <Check className="size-3.5 text-green-500" />
            : <Wrench className="size-3.5 text-amber-500" />
          }
        </div>

        <div className="flex max-w-[85%] flex-col gap-1.5">
          <div className={cn(
            "flex items-center gap-2 rounded-2xl rounded-tl-md border px-4 py-2.5 text-sm",
            healDone
              ? "border-green-500/20 bg-green-500/10 text-green-500"
              : "border-amber-500/20 bg-amber-500/10 text-amber-500"
          )}>
            {healDone
              ? <Check className="size-3.5 shrink-0" />
              : <Loader2 className="size-3.5 animate-spin shrink-0" />
            }
            <span className="font-medium">
              {healDone
                ? `Auto-fix applied (attempt ${attempt}/3)`
                : `Auto-fixing error (attempt ${attempt}/3)`
              }
            </span>
          </div>

          <span className="px-1 text-[10px] text-muted-foreground/60 opacity-0 transition-opacity group-hover:opacity-100">
            {formatTime(message.timestamp)}
          </span>
        </div>
      </div>
    );
  }

  // Render system messages (e.g. "Restored to version X") as centered cards
  if (message.role === "system") {
    return (
      <div className="group flex w-full flex-col items-center gap-1 animate-fade-in py-1">
        <div className="flex items-center gap-2 rounded-full border border-blue-500/20 bg-blue-500/10 px-4 py-2 text-xs text-blue-400">
          <RotateCcw className="size-3 shrink-0" />
          <span className="font-medium">{message.content}</span>
        </div>
        <span className="text-[10px] text-muted-foreground/60 opacity-0 transition-opacity group-hover:opacity-100">
          {formatTime(message.timestamp)}
        </span>
      </div>
    );
  }

  return (
    <div
      className={cn(
        "group flex gap-3 animate-fade-in",
        isUser ? "flex-row-reverse" : "flex-row"
      )}
    >
      {/* Avatar icon */}
      <div
        className={cn(
          "flex size-7 shrink-0 items-center justify-center rounded-lg",
          isUser
            ? "bg-primary text-primary-foreground"
            : "border border-border/50 bg-secondary"
        )}
      >
        {isUser ? <User className="size-3.5" /> : <Bot className="size-3.5" />}
      </div>

      {/* Message content */}
      <div
        className={cn(
          "flex max-w-[85%] flex-col gap-1.5",
          isUser ? "items-end" : "items-start"
        )}
      >
        {/* Model badge for AI messages */}
        {!isUser && message.model && (
          <Badge variant="secondary" className="text-[10px] px-1.5 py-0 font-normal">
            {formatModelName(message.model)}
          </Badge>
        )}

        {/* Image thumbnails for user messages with attached images */}
        {isUser && message.images && message.images.length > 0 && (
          <div className="flex flex-wrap gap-1.5 justify-end">
            {message.images.map((img, index) => (
              <button
                key={index}
                type="button"
                onClick={() => setSelectedImage(img)}
                className="size-16 cursor-pointer overflow-hidden rounded-lg border border-border/50 transition-transform duration-150 hover:scale-105"
              >
                <img
                  src={`data:${img.mediaType};base64,${img.base64}`}
                  alt={img.name || "Attached image"}
                  className="size-full object-cover"
                />
              </button>
            ))}
          </div>
        )}

        {/* Image lightbox dialog */}
        <Dialog open={!!selectedImage} onOpenChange={(open) => !open && setSelectedImage(null)}>
          <DialogContent
            className="max-w-[90vw] max-h-[90vh] p-0 border-none bg-transparent shadow-none sm:max-w-[90vw] overflow-hidden"
            showCloseButton
          >
            <DialogTitle className="sr-only">
              {selectedImage?.name || "Image preview"}
            </DialogTitle>
            {selectedImage && (
              <div className="flex flex-col items-center gap-2">
                <img
                  src={`data:${selectedImage.mediaType};base64,${selectedImage.base64}`}
                  alt={selectedImage.name || "Full size image"}
                  className="max-h-[85vh] max-w-full rounded-lg object-contain"
                />
                {selectedImage.name && (
                  <span className="text-xs text-muted-foreground">
                    {selectedImage.name}
                  </span>
                )}
              </div>
            )}
          </DialogContent>
        </Dialog>

        {/* Message bubble */}
        {isUser ? (
          <div className="rounded-2xl rounded-tr-md bg-primary px-4 py-2.5 text-sm leading-relaxed text-primary-foreground shadow-sm">
            <p className="whitespace-pre-wrap break-words">{displayContent}</p>
          </div>
        ) : (
          <div className="flex flex-col gap-2">
            {/* Explanation text in a card bubble */}
            {displayContent && (
              <div className="rounded-2xl rounded-tl-md border border-border/50 bg-card px-4 py-3 text-sm leading-relaxed shadow-sm">
                <div className="prose prose-sm dark:prose-invert max-w-none break-words [&>*:first-child]:mt-0 [&>*:last-child]:mb-0 [&_code]:rounded [&_code]:bg-secondary [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:text-xs [&_pre]:rounded-lg [&_pre]:border [&_pre]:border-border/50">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {displayContent}
                  </ReactMarkdown>
                  {/* Blinking cursor during streaming when no files yet */}
                  {isStreaming && !showProgress && (
                    <span className="ml-0.5 inline-block h-4 w-[2px] animate-pulse bg-primary align-middle" />
                  )}
                </div>
              </div>
            )}

            {/* Generation progress card — rendered outside the text bubble */}
            {(showProgress || isThinking) && (
              <GenerationProgress
                content={message.content}
                isStreaming={!!isStreaming}
                changedFiles={message.changedFiles}
              />
            )}
          </div>
        )}

        {/* Timestamp — shown on hover */}
        <span className="px-1 text-[10px] text-muted-foreground/60 opacity-0 transition-opacity group-hover:opacity-100">
          {formatTime(message.timestamp)}
        </span>
      </div>
    </div>
  );
}
