/**
 * 100 website prompts across different sectors.
 * Each entry has a thematic project name and a ~3 sentence description.
 */

export interface WebsitePrompt {
  sector: string;
  name: string;
  description: string;
}

export const PROMPTS: WebsitePrompt[] = [
  // ── Restaurant & Food ──────────────────────────────────────────────────────
  { sector: "Restaurant", name: "Bistro Milano", description: "A warm Italian restaurant website with a hero image of fresh pasta, a daily specials section, and an online reservation form. Use earthy tones like terracotta and olive green. Include a photo gallery of signature dishes." },
  { sector: "Restaurant", name: "Sushi Sakura", description: "A sleek Japanese sushi bar website with a dark theme, an interactive menu with prices, and a chef's story section. Add smooth scroll animations and a sticky navigation bar. Include an online ordering button." },
  { sector: "Bakery", name: "Golden Crust Bakery", description: "A charming bakery website with a pastel color scheme, a product carousel showing breads and pastries, and a weekly specials banner. Include customer testimonials and an embedded Google Maps location. Add an 'Order for Pickup' call-to-action." },
  { sector: "Food Truck", name: "Street Bites", description: "A fun and colorful food truck website with a live location tracker section, a photo-heavy menu grid, and social media feed integration. Use bold typography and bright orange accents. Include a catering inquiry form." },
  { sector: "Coffee Shop", name: "Bean & Brew", description: "A cozy coffee shop website with a warm brown palette, a menu section with hand-drawn style icons, and a loyalty program signup. Include a blog section for brewing tips and a store locator. Add an Instagram feed widget." },

  // ── Health & Wellness ──────────────────────────────────────────────────────
  { sector: "Fitness", name: "IronPulse Gym", description: "A high-energy fitness gym website with a bold black and red design, class schedules in a weekly calendar format, and trainer profile cards. Include a membership pricing table with three tiers and a free trial signup form. Add motivational before/after transformation photos." },
  { sector: "Yoga Studio", name: "Serene Flow Yoga", description: "A calming yoga studio website with soft lavender and sage green colors, a class timetable, and instructor bios with photos. Include a meditation resources section and an online booking system. Add gentle parallax scrolling effects." },
  { sector: "Dentist", name: "BrightSmile Dental", description: "A clean and professional dental clinic website with a light blue and white theme, a services overview with icons, and a patient testimonials slider. Include an emergency contact banner, insurance accepted list, and an appointment booking form." },
  { sector: "Therapist", name: "MindBridge Therapy", description: "A warm and approachable therapy practice website with calming earth tones, a services page describing different therapy modalities, and a confidential contact form. Include an FAQ section about what to expect in a first session. Add a resources page with helpful articles." },
  { sector: "Spa", name: "Tranquil Waters Spa", description: "A luxurious day spa website with a gold and cream color palette, a treatment menu with descriptions and prices, and a gift card purchase section. Include ambient background video of water features and a booking calendar. Add a virtual tour section." },

  // ── Technology & SaaS ──────────────────────────────────────────────────────
  { sector: "SaaS", name: "CloudSync Pro", description: "A modern SaaS landing page with a gradient hero section, feature cards with animated icons, and a three-tier pricing table. Include customer logos, an ROI calculator widget, and a live chat bubble. Use a clean sans-serif font and plenty of white space." },
  { sector: "AI Startup", name: "NeuralForge AI", description: "A cutting-edge AI company website with a dark futuristic theme, animated neural network graphics, and a product demo section with video. Include a technical blog, team page with headshots, and a contact form for enterprise inquiries. Add a careers section." },
  { sector: "Cybersecurity", name: "ShieldNet Security", description: "A professional cybersecurity firm website with a dark navy and neon green theme, a threat dashboard mockup, and a services breakdown page. Include trust badges, client case studies, and a free security audit request form. Add an incident response hotline banner." },
  { sector: "Dev Tools", name: "CodeForge CLI", description: "A developer tool landing page with a terminal-style hero section showing code snippets, a feature comparison table, and quick-start installation guide. Include syntax-highlighted code examples, a changelog section, and GitHub stars counter. Use a monospace font for headings." },
  { sector: "Cloud Hosting", name: "SkyHost Cloud", description: "A cloud hosting provider website with a blue sky gradient theme, a server plans comparison table, and an uptime guarantee banner. Include a data center locations map, a knowledge base section, and a migration assistance signup form. Add a status page link." },

  // ── Creative & Design ──────────────────────────────────────────────────────
  { sector: "Photography", name: "Lens & Light Studio", description: "A stunning photography portfolio website with a full-screen image gallery, a masonry grid layout for different shoots, and a booking inquiry form. Use minimal text with large visuals and smooth lightbox transitions. Include pricing packages and an about the photographer section." },
  { sector: "Architecture", name: "Vertex Architecture", description: "A sophisticated architecture firm website with a monochrome palette and bold geometric layouts, a portfolio grid of completed projects, and a design philosophy section. Include project case studies with before/after sliders and a contact page with office locations. Add awards and publications." },
  { sector: "Interior Design", name: "Casa Bella Interiors", description: "An elegant interior design studio website with a cream and gold palette, a portfolio carousel of room transformations, and a design process timeline. Include a style quiz for visitors, a materials library section, and a consultation booking form." },
  { sector: "Graphic Design", name: "PixelCraft Studio", description: "A creative graphic design agency website with a vibrant gradient background, a portfolio filterable by category, and a services page with pricing. Include client testimonials with project screenshots, a design process infographic, and a quick quote request form." },
  { sector: "Music Producer", name: "BeatLab Productions", description: "A music producer portfolio website with a dark theme and audio waveform visuals, an embedded music player with recent tracks, and a collaboration request form. Include a discography section, studio equipment list, and links to streaming platforms. Add animated equalizer graphics." },

  // ── Education ──────────────────────────────────────────────────────────────
  { sector: "Online Course", name: "SkillUp Academy", description: "An online learning platform landing page with a search bar hero, course cards with progress indicators, and instructor spotlight sections. Include student success stories, a pricing comparison for monthly vs yearly plans, and a free trial signup. Use bright blue and orange accents." },
  { sector: "Language School", name: "LinguaBridge", description: "A language school website with a world map hero graphic, course offerings by language with level indicators, and a placement test call-to-action. Include native teacher profiles, student review cards, and a class schedule calendar. Add a free first lesson offer." },
  { sector: "Tutoring", name: "BrainSpark Tutoring", description: "A private tutoring service website with a friendly green and white theme, subject cards for math, science, and languages, and a tutor matching form. Include parent testimonials, a results statistics section, and flexible scheduling options. Add a free consultation offer." },
  { sector: "Coding Bootcamp", name: "HackPath Academy", description: "A coding bootcamp website with a dark terminal-inspired design, a curriculum roadmap timeline, and alumni success stories with job placement stats. Include a tech stack icon grid, scholarship information, and an application form. Add a live cohort countdown timer." },
  { sector: "Kindergarten", name: "Little Explorers", description: "A cheerful kindergarten website with playful illustrations and rainbow colors, an activities calendar, and a virtual classroom tour section. Include teacher profiles with fun facts, a parent portal login area, and an enrollment form. Add a photo gallery of events." },

  // ── Real Estate ────────────────────────────────────────────────────────────
  { sector: "Real Estate", name: "PrimeNest Realty", description: "A premium real estate agency website with a property search hero with filters, a featured listings grid with photos and prices, and an agent directory. Include a mortgage calculator widget, neighborhood guide pages, and a property valuation request form." },
  { sector: "Property Management", name: "UrbanKey Properties", description: "A property management company website with a clean blue and gray theme, a tenant portal section, and a landlord services overview. Include a maintenance request form, available properties listings, and a FAQ for both tenants and owners. Add a testimonials section." },
  { sector: "Interior Staging", name: "StageRight Homes", description: "A home staging company website with beautiful before and after photo sliders, a portfolio of staged homes, and a pricing packages section. Include the staging process explained in steps, client reviews, and a free consultation booking form. Use elegant typography." },
  { sector: "Construction", name: "SolidBuild Construction", description: "A construction company website with a bold industrial design, a project portfolio with completion timelines, and a services page covering residential and commercial work. Include safety certifications, a team page, and a project quote request form. Add a progress tracking section." },
  { sector: "Vacation Rental", name: "SeaBreeze Villas", description: "A vacation rental website with a stunning beach hero image, a property grid with availability calendars, and a quick booking form. Include guest reviews, a local attractions guide, and a virtual property tour. Use tropical colors and relaxed typography." },

  // ── E-commerce & Retail ────────────────────────────────────────────────────
  { sector: "Fashion", name: "Velvet & Thread", description: "A fashion boutique website with a minimalist black and white design, a new arrivals carousel, and a lookbook gallery section. Include size guide, shipping information, and a newsletter signup with a discount offer. Add a trending now section." },
  { sector: "Jewelry", name: "Lumière Jewels", description: "A luxury jewelry brand website with a dark background and gold accents, a product showcase with zoom functionality mockup, and a custom design inquiry form. Include a craftsmanship story section, a gift guide, and an appointment booking for in-store visits." },
  { sector: "Pet Store", name: "PawPalace", description: "A fun pet store website with a playful design using paw print patterns, a product grid organized by pet type, and a pet adoption section. Include a pet care blog, a loyalty rewards explanation, and a store locator. Use warm orange and teal colors." },
  { sector: "Bookstore", name: "PageTurner Books", description: "A cozy independent bookstore website with a vintage paper texture background, a staff picks carousel, and a book club signup section. Include an events calendar for author readings, a genre-based browsing section, and a gift card purchase area. Add a reading list builder." },
  { sector: "Plant Shop", name: "Urban Jungle Plants", description: "A fresh plant shop website with a lush green color palette, a plant care difficulty filter, and a subscription box signup for monthly plant deliveries. Include care guides for each plant category, a plant parent quiz, and a customer plant photo gallery." },

  // ── Professional Services ──────────────────────────────────────────────────
  { sector: "Law Firm", name: "Juris & Partners", description: "A prestigious law firm website with a navy and gold color scheme, practice areas with detailed descriptions, and attorney profile pages. Include a case results section, a client intake form, and an FAQ about legal processes. Add a free consultation offer banner." },
  { sector: "Accounting", name: "ClearBooks Accounting", description: "A trustworthy accounting firm website with a clean green and white design, a services grid for tax, audit, and advisory, and a client portal login. Include industry-specific expertise sections, a tax deadline calendar, and a free consultation request form." },
  { sector: "Consulting", name: "StratEdge Consulting", description: "A sharp management consulting website with a dark blue and white theme, a methodology overview diagram, and industry expertise cards. Include a case study showcase, a team page with credentials, and a project inquiry form. Add thought leadership articles." },
  { sector: "Insurance", name: "SafeHaven Insurance", description: "A reassuring insurance agency website with a light blue and white palette, a quote comparison tool layout, and a claims process timeline. Include coverage type explanations, customer testimonial videos placeholder, and an agent finder by zip code. Add a disaster preparedness resources section." },
  { sector: "Recruitment", name: "TalentBridge HR", description: "A dynamic recruitment agency website with a modern purple and teal gradient, a job board with filter options, and an employer partnership section. Include candidate success stories, industry specialization pages, and a resume upload form. Add a salary guide download." },

  // ── Nonprofit & Community ──────────────────────────────────────────────────
  { sector: "Nonprofit", name: "GreenEarth Foundation", description: "An impactful environmental nonprofit website with nature imagery, a mission statement hero, and a donation form with suggested amounts. Include project impact statistics with animated counters, a volunteer signup section, and an events calendar. Add a newsletter subscription." },
  { sector: "Animal Shelter", name: "FurEver Home Shelter", description: "A heartwarming animal shelter website with a hero featuring adoptable pets, a filterable gallery of animals by species and age, and an adoption application form. Include success stories with before/after photos, a donation section, and a volunteer schedule. Use warm pastel colors." },
  { sector: "Church", name: "Grace Community Church", description: "A welcoming church website with a warm wood and light theme, a weekly service schedule, and a sermon archive section. Include a newcomer welcome page, small groups directory, and a prayer request form. Add an events calendar and a giving page." },
  { sector: "Youth Organization", name: "NextGen Youth Club", description: "An energetic youth organization website with bold colors and dynamic shapes, a programs overview with age groups, and a registration form. Include a photo gallery of past events, a mentor profiles section, and a parent information page. Add a calendar of upcoming activities." },
  { sector: "Food Bank", name: "Harvest Hope Food Bank", description: "A compassionate food bank website with warm yellow and green colors, a donation impact calculator, and a volunteer shift signup calendar. Include a food drive toolkit download, a distribution center locator, and partner organization logos. Add a stories of impact section." },

  // ── Travel & Hospitality ───────────────────────────────────────────────────
  { sector: "Hotel", name: "Azure Bay Resort", description: "A luxurious resort website with a full-width ocean hero video placeholder, a room types comparison grid, and an amenities showcase. Include a virtual tour section, a dining and spa page, and a booking form with date picker. Use a sophisticated blue and cream palette." },
  { sector: "Travel Agency", name: "Wanderlust Voyages", description: "An adventurous travel agency website with a world map hero, a destination cards grid with stunning photos, and a trip planner form. Include travel packages with pricing, customer travel diaries section, and a newsletter with travel deals. Add a trending destinations section." },
  { sector: "Tour Guide", name: "CityWalks Tours", description: "A friendly walking tour company website with a city skyline hero, a tours catalog by city and theme, and a booking calendar. Include guide profiles with languages spoken, customer reviews with ratings, and a group booking discount section. Add a photo gallery from tours." },
  { sector: "Camping", name: "WildTrail Camping", description: "A rugged outdoor camping website with a forest hero image, a campsite listings page with amenities icons, and a gear checklist download. Include a trail difficulty guide, a weather conditions widget area, and a reservation form. Use earthy browns and forest greens." },
  { sector: "Airline", name: "SkyBridge Airlines", description: "A sleek airline website with a flight search hero form, a destinations grid with promotional fares, and a loyalty program overview. Include a fleet information page, travel requirements section, and a check-in button. Use a modern blue and white design with cloud illustrations." },

  // ── Automotive ─────────────────────────────────────────────────────────────
  { sector: "Car Dealership", name: "AutoElite Motors", description: "A premium car dealership website with a rotating hero showing featured vehicles, an inventory browser with filter by make and price, and a financing calculator. Include a trade-in value estimator, a service appointment scheduler, and customer reviews. Use a sleek dark theme." },
  { sector: "Auto Repair", name: "QuickFix Garage", description: "A trustworthy auto repair shop website with a clean red and gray theme, a services menu with transparent pricing, and an appointment booking form. Include a mechanic team page, a car care tips blog, and a loyalty discount program. Add a roadside assistance number banner." },
  { sector: "Car Wash", name: "SparkleShine Car Wash", description: "A fresh car wash website with a blue water splash theme, a wash packages comparison table, and a membership subscription section. Include a monthly unlimited wash pass offer, a before/after gallery, and a location finder with hours. Add an eco-friendly practices section." },
  { sector: "Motorcycle", name: "ThunderRide Motorcycles", description: "A bold motorcycle shop website with a matte black design and chrome accents, a bike gallery with specifications, and a parts catalog section. Include a community rides calendar, a custom build request form, and a rider gear showcase. Add a financing options page." },
  { sector: "EV Charging", name: "VoltPoint Charging", description: "A clean electric vehicle charging network website with a green energy theme, a station locator map, and a pricing plan comparison. Include a network coverage statistics section, a business partnership inquiry form, and a mobile app download section. Add an environmental impact counter." },

  // ── Sports & Recreation ────────────────────────────────────────────────────
  { sector: "Sports Club", name: "Summit Athletic Club", description: "A dynamic sports club website with an energetic red and black theme, a class schedule calendar, and a facilities virtual tour section. Include membership tiers with pricing, a personal training booking system, and member testimonials. Add a club news and events feed." },
  { sector: "Dance Studio", name: "Rhythmic Arts Dance", description: "A graceful dance studio website with an elegant pink and purple gradient, a class offerings grid by dance style, and a performance calendar. Include instructor profiles with specialties, a student showcase video gallery, and a trial class registration form." },
  { sector: "Golf Course", name: "Emerald Fairways Golf", description: "A prestigious golf course website with a green and white classic design, a course overview with hole-by-hole descriptions, and a tee time booking system. Include membership information, a pro shop section, and a tournament calendar. Add a course conditions update area." },
  { sector: "Martial Arts", name: "Dragon Spirit Dojo", description: "A powerful martial arts school website with a red and black design, a programs section for different age groups and belt levels, and a trial class signup form. Include instructor credentials, a belt progression chart, and a competition results page. Add a philosophy section." },
  { sector: "Skating Rink", name: "IceGlide Arena", description: "A cool skating rink website with an icy blue and silver theme, a public skating schedule, and a birthday party packages section. Include figure skating and hockey programs, a pro shop section, and a group booking form. Add a winter break special events calendar." },

  // ── Beauty & Personal Care ─────────────────────────────────────────────────
  { sector: "Hair Salon", name: "Luxe Locks Salon", description: "A stylish hair salon website with a rose gold and black theme, a services menu with starting prices, and a stylist portfolio carousel. Include an online booking system with stylist selection, a hair care tips blog, and a loyalty rewards section. Add a first visit discount offer." },
  { sector: "Barbershop", name: "Classic Cuts Barber", description: "A vintage-inspired barbershop website with a wood and leather texture theme, a services list with prices, and a barber team page. Include a walk-in vs appointment section, a grooming products showcase, and a gallery of haircut styles. Add a gentleman's club membership." },
  { sector: "Nail Salon", name: "Polished Nail Bar", description: "A chic nail salon website with a soft pink and white design, a nail art gallery, and a services pricing page. Include an online booking with time slot selection, a seasonal nail trends section, and a gift certificate purchase option. Add a hygiene and safety practices page." },
  { sector: "Skincare", name: "GlowUp Skincare", description: "A clean skincare brand website with a minimal white and green design, a product line showcase with ingredient highlights, and a skin type quiz. Include a before/after results gallery, a skincare routine builder, and a subscription box offer. Add a dermatologist endorsement section." },
  { sector: "Tattoo Studio", name: "InkCraft Tattoo", description: "An edgy tattoo studio website with a dark grunge aesthetic, an artist portfolio gallery organized by style, and a consultation booking form. Include a tattoo aftercare guide, a flash designs section with pricing, and artist interview articles. Add a studio tour virtual walkthrough." },

  // ── Events & Entertainment ─────────────────────────────────────────────────
  { sector: "Wedding Planner", name: "Bliss & Bloom Weddings", description: "A romantic wedding planning website with a soft blush and ivory color scheme, a services packages comparison, and a real weddings gallery. Include a planning checklist tool, a vendor directory section, and a contact form with event date picker. Add a blog with wedding inspiration." },
  { sector: "Event Venue", name: "The Grand Pavilion", description: "An elegant event venue website with a gold and marble aesthetic, a virtual venue tour section, and a capacity and floor plans page. Include an events gallery sorted by type, a catering menu section, and an availability inquiry form. Add a testimonials carousel from past events." },
  { sector: "DJ Service", name: "BassWave DJs", description: "An exciting DJ service website with a neon and dark theme, a music genre specialties section, and a booking form with event details. Include a video highlights reel from past events, a client review wall, and equipment list. Add a sample mix player." },
  { sector: "Photo Booth", name: "SnapBox Photo Booths", description: "A fun photo booth rental website with a colorful confetti design, a booth styles gallery, and a rental packages comparison table. Include a prop catalog, a backdrop options section, and an instant quote calculator. Add a sample photo gallery from events." },
  { sector: "Festival", name: "SoundWave Festival", description: "A vibrant music festival website with a psychedelic gradient design, a lineup announcement section with artist cards, and a ticket tiers comparison. Include a festival map, a FAQ page for attendees, and a volunteer signup form. Add a countdown timer to the event date." },

  // ── Home Services ──────────────────────────────────────────────────────────
  { sector: "Plumbing", name: "FlowRight Plumbing", description: "A reliable plumbing services website with a blue and white clean design, a service list with emergency availability highlighted, and a quick quote request form. Include a service area map, a tips and maintenance blog, and a satisfaction guarantee badge. Add customer review cards." },
  { sector: "Electrician", name: "BrightWire Electric", description: "A professional electrician website with a yellow and dark gray theme, a residential and commercial services breakdown, and a 24/7 emergency call banner. Include a project gallery, a safety tips section, and a free estimate request form. Add licensing and insurance information." },
  { sector: "Landscaping", name: "EverGreen Landscapes", description: "A fresh landscaping company website with a lush green and earthy brown theme, a services gallery with before/after project photos, and a seasonal maintenance plan section. Include a design consultation booking form, a portfolio of garden styles, and a blog with gardening tips." },
  { sector: "Cleaning Service", name: "SparkleHome Cleaning", description: "A crisp cleaning service website with a light blue and white design, a services grid for residential, commercial, and move-in/out cleaning, and an instant pricing estimator. Include a booking form with recurring schedule options, eco-friendly products section, and a trust badge area." },
  { sector: "Moving Company", name: "SwiftMove Logistics", description: "A dependable moving company website with a bold orange and navy theme, a services page for local, long-distance, and office moves, and an instant quote calculator by home size. Include a packing tips section, a moving day checklist download, and a customer stories page." },

  // ── Agriculture & Farm ─────────────────────────────────────────────────────
  { sector: "Farm", name: "Sunrise Organic Farm", description: "A wholesome organic farm website with a warm sunflower yellow and green theme, a seasonal produce calendar, and a farm-to-table story section. Include a CSA subscription signup, a farm visit booking form, and a recipe blog. Add a virtual farm tour with drone footage placeholder." },
  { sector: "Winery", name: "Vineyard Hills Winery", description: "A sophisticated winery website with a deep burgundy and cream palette, a wine collection grid with tasting notes, and a wine club membership section. Include a virtual tasting booking, a vineyard events calendar, and a visit planning page with directions. Add a wine pairing guide." },
  { sector: "Florist", name: "Petal & Stem Florals", description: "A beautiful florist website with a romantic watercolor floral background, an arrangement gallery sorted by occasion, and a custom order request form. Include a delivery area map, a flower care guide, and a subscription bouquet service. Add a wedding flowers portfolio section." },
  { sector: "Brewery", name: "Copper Kettle Brewery", description: "A craft brewery website with a rustic wood and copper theme, a beer lineup with IBU and ABV details, and a taproom events calendar. Include a brewery tour booking, a merchandise shop section, and a homebrew tips blog. Add a find our beer on tap locator." },
  { sector: "Beekeeping", name: "Golden Hive Apiary", description: "A sweet beekeeping farm website with a honeycomb pattern design in amber and white, a honey products showcase, and a bee adoption program section. Include a pollination services page for farmers, an educational bee facts section, and an online ordering form." },

  // ── Media & Publishing ─────────────────────────────────────────────────────
  { sector: "Podcast", name: "The Deep Dive Podcast", description: "A modern podcast website with a dark theme and audio waveform graphics, an episodes grid with play buttons and show notes, and a guest application form. Include a host bio section, a subscribe links bar for all platforms, and a newsletter signup. Add a merch section." },
  { sector: "Blog", name: "TechPulse Blog", description: "A clean tech blog website with a white and blue minimal design, a latest articles hero section, and a category sidebar with tags. Include an author profiles page, a newsletter popup, and a trending articles section. Add a reading time indicator on each post." },
  { sector: "Magazine", name: "Vogue Urbaine", description: "A high-fashion digital magazine website with a dramatic black and white layout, a cover story hero section, and a content grid sorted by category. Include a subscribe section, a contributors page, and a trending topics bar. Add a search with autocomplete." },
  { sector: "News Portal", name: "Daily Chronicle", description: "A professional news portal website with a classic newspaper layout, a breaking news ticker, and categorized article sections for politics, tech, and sports. Include a live updates section, an opinion columns area, and a reader comments section. Add a dark mode toggle." },
  { sector: "Video Production", name: "FrameForge Films", description: "A cinematic video production company website with a dark widescreen layout, a showreel hero video, and a portfolio grid sorted by project type. Include a production process timeline, a client list with logos, and a project inquiry form. Add behind-the-scenes stills." },

  // ── Finance ────────────────────────────────────────────────────────────────
  { sector: "Fintech", name: "PayFlow Digital", description: "A sleek fintech landing page with a gradient blue hero, a product features section with animated icons, and a security trust badges area. Include a demo request form, API documentation preview, and a pricing table for different business sizes. Add a partner integration logos section." },
  { sector: "Crypto", name: "BlockVault Exchange", description: "A futuristic cryptocurrency platform website with a dark navy and neon accent theme, a live price ticker mockup, and a features overview grid. Include a security section with audit badges, a getting started guide, and a referral program. Add a mobile app download section." },
  { sector: "Investment", name: "WealthPeak Advisors", description: "A sophisticated investment advisory website with a deep green and gold palette, a services overview for retirement, estate, and tax planning, and an advisor team page. Include a portfolio performance chart area, a client portal login, and a consultation booking form." },
  { sector: "Banking", name: "TrustCore Bank", description: "A modern digital bank website with a clean blue gradient design, a product cards section for accounts, loans, and credit cards, and a rates comparison table. Include a mobile banking features showcase, a branch and ATM locator, and an account opening flow. Add a financial literacy resources section." },
  { sector: "Tax Service", name: "TaxEase Solutions", description: "A professional tax preparation website with a green and white clean design, a services grid for personal, business, and international tax, and a document upload section. Include a tax deadline calendar, a savings calculator, and a free consultation offer. Add client testimonials." },

  // ── Logistics & Industrial ─────────────────────────────────────────────────
  { sector: "Logistics", name: "FastTrack Logistics", description: "A professional logistics company website with a dark blue and orange theme, a shipment tracking form, and a services overview for freight, warehousing, and distribution. Include a coverage area map, a fleet showcase, and a quick quote form. Add a client portal login." },
  { sector: "Warehouse", name: "VaultSpace Storage", description: "A clean self-storage facility website with a blue and gray industrial design, a unit sizes comparison table with pricing, and a location finder. Include a space calculator, a packing supplies section, and an online reservation form. Add security features and access hours." },
  { sector: "Manufacturing", name: "PrecisionWorks Mfg", description: "A solid manufacturing company website with a steel gray and blue theme, a capabilities section with process descriptions, and a product catalog grid. Include a quality certifications page, a facility virtual tour, and an RFQ form. Add a case studies section." },
  { sector: "Shipping", name: "OceanBridge Shipping", description: "A global shipping company website with a deep blue ocean theme, a rate calculator by route and container size, and a service routes map. Include a container tracking form, a documentation guides section, and a partner port network page. Add an environmental sustainability section." },
  { sector: "Solar Energy", name: "SunPower Solutions", description: "A bright solar energy company website with a sunny yellow and white theme, a solar savings calculator, and a residential vs commercial services comparison. Include an installation process timeline, a financing options page, and a free site assessment form. Add a customer installations gallery." },

  // ── Gaming & Entertainment ─────────────────────────────────────────────────
  { sector: "Gaming", name: "PixelRealm Games", description: "An immersive game studio website with a dark purple and neon theme, a game showcase carousel with trailers, and a community forum section. Include a dev blog with updates, a press kit download area, and a careers page. Add a Discord community join button." },
  { sector: "Escape Room", name: "MindTrap Escape", description: "A mysterious escape room website with a dark theme and lock/key graphics, a room themes gallery with difficulty ratings, and a group booking form. Include a how it works section, a leaderboard for fastest times, and a gift voucher purchase page. Add a corporate team building section." },
  { sector: "Board Game Cafe", name: "DiceDen Cafe", description: "A fun board game cafe website with a colorful tabletop theme, a game library searchable by player count, and a table reservation system. Include a food and drinks menu, a game night events calendar, and a membership pass section. Add a game recommendation quiz." },
  { sector: "Cinema", name: "Lumière Cinema", description: "A sleek independent cinema website with a dark theme and spotlight accents, a now showing section with movie posters and showtimes, and a coming soon preview area. Include a membership club, a concessions menu, and a private screening booking form. Add a film festival section." },
  { sector: "Theme Park", name: "AdventureWorld Park", description: "A thrilling theme park website with a vibrant rainbow gradient design, a rides and attractions gallery with height requirements, and a ticket pricing calculator. Include a park map download, a shows and events schedule, and a season pass comparison. Add a real-time wait times section." },

  // ── Miscellaneous ──────────────────────────────────────────────────────────
  { sector: "Coworking", name: "HiveSpace Coworking", description: "A modern coworking space website with a warm wood and white aesthetic, a desk and office plans comparison table, and a virtual tour section. Include a community events calendar, a member perks page, and a day pass booking form. Add a startup resources section." },
  { sector: "Laundromat", name: "FreshSpin Laundry", description: "A clean laundromat website with a fresh aqua and white theme, a wash and fold pricing table, and a pickup and delivery scheduling form. Include a machine availability status mockup, a loyalty points program, and a location hours page. Add a stain removal tips section." },
  { sector: "Veterinary", name: "PawCare Vet Clinic", description: "A friendly veterinary clinic website with a soft green and paw print design, a services page for wellness, surgery, and dental, and an appointment booking form. Include a pet health resources section, an emergency care banner, and a new patient registration form. Add a team page with staff pets." },
  { sector: "Museum", name: "Heritage Arts Museum", description: "A refined museum website with a marble and dark theme, a current exhibitions showcase, and a ticket booking system with date and time selection. Include a permanent collection gallery, an educational programs section, and a membership benefits page. Add a virtual exhibit tour." },
  { sector: "Library", name: "Oakwood Public Library", description: "A welcoming public library website with a warm sepia and cream design, a catalog search bar hero, and a new arrivals section. Include a programs and events calendar, a digital resources page, and a library card signup form. Add a reading challenges section for kids and adults." },
];
