export interface Product {
  id: string;
  name: string;
  inspiredBy: string;
  price: number;
  originalPrice?: number;
  category: 'dames' | 'heren' | 'unisex' | 'niche' | 'extract' | 'exclusive';
  isBestseller?: boolean;
  isNew?: boolean;
  isSoldOut?: boolean;
  rating: number;
  reviewCount: number;
  image: string;
  notes: {
    top: string[];
    heart: string[];
    base: string[];
  };
  description: string;
  size: string;
  longevity: string;
  sillage: string;
}

export interface Category {
  id: string;
  name: string;
  slug: string;
  image: string;
  count: number;
  description: string;
}

export const products: Product[] = [
  {
    id: '309',
    name: '309',
    inspiredBy: 'Libre – YSL',
    price: 24.95,
    category: 'dames',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 847,
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80',
    notes: { top: ['Mandarin', 'Lavender'], heart: ['Jasmine', 'Orange Blossom'], base: ['Vanilla', 'Ambergris'] },
    description: 'Een vrijgevochten en sensuele geur die kracht en feminiteit combineert.',
    size: '50ml',
    longevity: '8-10 uur',
    sillage: 'Sterk',
  },
  {
    id: '307',
    name: '307',
    inspiredBy: 'Black Opium – YSL',
    price: 24.95,
    category: 'dames',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 1203,
    image: '',
    notes: { top: ['Pink Pepper', 'Orange Blossom'], heart: ['Coffee', 'Jasmine'], base: ['Vanilla', 'Patchouli', 'Cedarwood'] },
    description: 'Verslavend, warm en diep — een geur die blijft hangen.',
    size: '50ml',
    longevity: '10-12 uur',
    sillage: 'Intens',
  },
  {
    id: '045',
    name: '045',
    inspiredBy: 'Coco Mademoiselle – Chanel',
    price: 24.95,
    category: 'dames',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 965,
    image: '',
    notes: { top: ['Orange', 'Bergamot'], heart: ['Rose', 'Jasmine', 'Ylang-Ylang'], base: ['Patchouli', 'Vetiver', 'Vanilla'] },
    description: 'Tijdloos elegant — een klassieker die generaties overstijgt.',
    size: '50ml',
    longevity: '8-10 uur',
    sillage: 'Matig tot sterk',
  },
  {
    id: '263',
    name: '263',
    inspiredBy: 'Paradoxe – Prada',
    price: 24.95,
    category: 'dames',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 632,
    image: '',
    notes: { top: ['Neroli', 'Bergamot'], heart: ['White Musks', 'Iris'], base: ['Sandalwood', 'Amberwood'] },
    description: 'Modern, complex en onweerstaanbaar — een ode aan vrouwelijkheid.',
    size: '50ml',
    longevity: '8-10 uur',
    sillage: 'Matig',
  },
  {
    id: '105',
    name: '105',
    inspiredBy: 'Stronger With You – Armani',
    price: 24.95,
    category: 'heren',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 789,
    image: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&q=80',
    notes: { top: ['Pink Pepper', 'Sage'], heart: ['Chestnut', 'Lavender'], base: ['Vanilla', 'Sandalwood', 'Cashmere Wood'] },
    description: 'Warm, kruidig en onweerstaanbaar maskulien. De geur van vertrouwen.',
    size: '50ml',
    longevity: '8-10 uur',
    sillage: 'Matig tot sterk',
  },
  {
    id: '210',
    name: '210',
    inspiredBy: 'Arabian Tonka – Initio',
    price: 24.95,
    category: 'unisex',
    isBestseller: true,
    rating: 5.0,
    reviewCount: 412,
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80',
    notes: { top: ['Mandarine', 'Bergamot'], heart: ['Tonka Bean', 'Heliotrope'], base: ['Musk', 'Amber', 'Vanilla'] },
    description: 'Oosters rijkdom ontmoet moderne elegantie in deze exclusieve compositie.',
    size: '50ml',
    longevity: '10-12 uur',
    sillage: 'Intens',
  },
  {
    id: '272',
    name: '272',
    inspiredBy: 'Tobacco Vanille – Tom Ford',
    price: 24.95,
    category: 'niche',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 556,
    image: 'https://images.unsplash.com/photo-1542202229-7d93c33f5d07?w=600&q=80',
    notes: { top: ['Tobacco', 'Spicy Notes'], heart: ['Tonka Bean', 'Tobacco Flower'], base: ['Vanilla', 'Cacao', 'Wood Sap'] },
    description: 'Luxueus, warm en complex — een sensuele niche creatie voor kenners.',
    size: '50ml',
    longevity: '12+ uur',
    sillage: 'Zeer sterk',
  },
  {
    id: '203',
    name: '203',
    inspiredBy: 'Ombre Nomade – Louis Vuitton',
    price: 24.95,
    category: 'niche',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 387,
    image: 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=600&q=80',
    notes: { top: ['Birch Tar', 'Oud'], heart: ['Rose', 'Geranium'], base: ['Benzoin', 'Labdanum'] },
    description: 'Een diep rookachtig oud-parfum dat avontuur en luxe ademt.',
    size: '50ml',
    longevity: '12+ uur',
    sillage: 'Intens',
  },
  {
    id: 'enchant',
    name: 'Enchant',
    inspiredBy: 'Baccarat Rouge 540 – Maison Francis Kurkdjian',
    price: 42.49,
    category: 'exclusive',
    isBestseller: true,
    rating: 5.0,
    reviewCount: 1456,
    image: 'https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=600&q=80',
    notes: { top: ['Saffron', 'Jasmine'], heart: ['Amberwood', 'Fir Resin'], base: ['Erythoxylum', 'Cedar'] },
    description: 'De iconische geur van onze tijd. Verblindend, warm, en onvergetelijk.',
    size: '50ml',
    longevity: '12+ uur',
    sillage: 'Zeer sterk',
  },
  {
    id: 'belong',
    name: 'Belong',
    inspiredBy: 'Angel Share – Kilian',
    price: 42.49,
    category: 'exclusive',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 892,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80',
    notes: { top: ['Cognac', 'Cinnamon'], heart: ['Praline', 'Tonka Bean'], base: ['Sandalwood', 'Vanilla', 'Caramel'] },
    description: 'Warm en zoet als een omhelzing — een geur die raakt aan de ziel.',
    size: '50ml',
    longevity: '10-12 uur',
    sillage: 'Sterk',
  },
  {
    id: 'feel',
    name: 'Feel',
    inspiredBy: 'Erba Pura – Xerjoff',
    price: 42.49,
    category: 'exclusive',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 743,
    image: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=600&q=80',
    notes: { top: ['Sicilian Mandarin', 'Lemon'], heart: ['White Musk', 'Sandalwood'], base: ['Ambroxan', 'Vanilla'] },
    description: 'Fris, bloemig en warm — een sinnelijke mediterrane odyssee.',
    size: '50ml',
    longevity: '10-12 uur',
    sillage: 'Sterk',
  },
  {
    id: 'cherry',
    name: 'Cherry',
    inspiredBy: 'Lost Cherry – Tom Ford',
    price: 42.49,
    category: 'exclusive',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 621,
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&q=80',
    notes: { top: ['Cherry Liqueur', 'Bitter Almond'], heart: ['Turkish Rose', 'Jasmine'], base: ['Benzoin', 'Sandalwood', 'Tonka Bean'] },
    description: 'Speels en sensueel — een verleidelijke dans van kers en musk.',
    size: '50ml',
    longevity: '10-12 uur',
    sillage: 'Matig tot sterk',
  },
];

export const categories: Category[] = [
  {
    id: 'dames',
    name: 'Dames',
    slug: 'dames',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&q=80',
    count: 89,
    description: 'Elegante en vrouwelijke geuren',
  },
  {
    id: 'heren',
    name: 'Heren',
    slug: 'heren',
    image: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&q=80',
    count: 76,
    description: 'Krachtige en maskuliene geuren',
  },
  {
    id: 'unisex',
    name: 'Unisex',
    slug: 'unisex',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683702?w=800&q=80',
    count: 45,
    description: 'Voor iedereen, zonder grenzen',
  },
  {
    id: 'niche',
    name: 'Niche',
    slug: 'niche',
    image: 'https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=800&q=80',
    count: 32,
    description: 'Zeldzame en exclusieve composities',
  },
  {
    id: 'extract',
    name: 'Extract',
    slug: 'extract',
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80',
    count: 18,
    description: 'Maximale concentratie, ultiem genot',
  },
  {
    id: 'exclusive',
    name: 'Exclusive',
    slug: 'exclusive',
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&q=80',
    count: 14,
    description: 'Onze premium collectie',
  },
  {
    id: 'home',
    name: 'Home & Lifestyle',
    slug: 'home-lifestyle',
    image: 'https://images.unsplash.com/photo-1616103570498-a7d34e7b4f49?w=800&q=80',
    count: 28,
    description: 'Luxe geurervaringen voor thuis',
  },
];

export const reviews = [
  {
    id: 1,
    name: 'Sophie V.',
    location: 'Amsterdam',
    rating: 5,
    date: '15 maart 2026',
    title: 'Absoluut geweldig!',
    text: 'Ik was sceptisch, maar dit parfum is echt ongelooflijk. Ruikt precies zoals het origineel maar voor een fractie van de prijs. Iedereen vraagt me welk parfum ik draag!',
    product: '309 – Geïnspireerd door Libre',
    verified: true,
  },
  {
    id: 2,
    name: 'Lars M.',
    location: 'Rotterdam',
    rating: 5,
    date: '8 maart 2026',
    title: 'Kwaliteit overtreft de prijs',
    text: 'Mijn derde bestelling al. De kwaliteit is consistent hoog, de houdbaarheid is geweldig — ik ruik de hele dag heerlijk. Aanrader voor iedereen die luxe geur zoekt zonder de luxe prijs.',
    product: '105 – Geïnspireerd door Stronger With You',
    verified: true,
  },
  {
    id: 3,
    name: 'Emma K.',
    location: 'Utrecht',
    rating: 5,
    date: '2 maart 2026',
    title: 'Precies wat ik zocht',
    text: 'Enchant is mijn absolute favoriet geworden. Warm, sensueel en zo langdurig. Ik krijg constant complimenten. De verpakking is ook erg mooi, ideaal als cadeautje!',
    product: 'Enchant – Geïnspireerd door Baccarat Rouge 540',
    verified: true,
  },
  {
    id: 4,
    name: 'Daan R.',
    location: 'Den Haag',
    rating: 5,
    date: '28 februari 2026',
    title: 'Snelle levering, top kwaliteit',
    text: 'Voor 17:30 besteld en de volgende dag al in huis! Het parfum zelf is prachtig. Ik heb Tobacco Vanille genomen en het is perfect. Rijkelijk, warm en echt premium.',
    product: '272 – Geïnspireerd door Tobacco Vanille',
    verified: true,
  },
  {
    id: 5,
    name: 'Mila S.',
    location: 'Eindhoven',
    rating: 5,
    date: '20 februari 2026',
    title: 'Echt een aanrader!',
    text: 'Ik ben zo blij dat ik dit ontdekt heb. De 2+1 aanbieding is geweldig — ik heb drie geuren mee kunnen nemen. Allemaal top kwaliteit en de houdbaarheid is echt indrukwekkend.',
    product: '045 – Geïnspireerd door Coco Mademoiselle',
    verified: true,
  },
];

export const announcementMessages = [
  'Gratis verzending vanaf €50',
  'Voor 17:30 besteld, morgen in huis',
  'Betaal achteraf met Klarna',
  'Alle parfums 2+1 gratis',
];
