#!/bin/sh
# Generate .dev.vars from environment variables for wrangler dev
cat > /app/.dev.vars << VARS
CLERK_ISSUER=${CLERK_ISSUER}
CLERK_JWKS_URL=${CLERK_JWKS_URL}
GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
CLERK_WEBHOOK_SECRET=${CLERK_WEBHOOK_SECRET}
TURSO_API_TOKEN=${TURSO_API_TOKEN}
TURSO_API_URL=${TURSO_API_URL}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
STRIPE_CLIENT_ID=${STRIPE_CLIENT_ID}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
COOLIFY_API_KEY=${COOLIFY_API_KEY}
COOLIFY_URL=${COOLIFY_URL}
DEPLOYMENT_GITHUB_TOKEN=${DEPLOYMENT_GITHUB_TOKEN}
DEPLOYMENT_REPO=${DEPLOYMENT_REPO}
FRONTEND_URL=${FRONTEND_URL}
VARS

exec npx wrangler dev --local --port 8787 --ip 0.0.0.0
